### PR TITLE
Suggestions and additional technique presentation

### PR DESCRIPTION
**Pull request by fekete965**
Some of the code could look intimidating, but please don't get scared.
I recommend reading it through commit by commit and playing with the code itself! :)
I am more than happy to explain each commit and the changes to you either in text or on a call whichever you prefer.
These changes are not necessary at all, your application works just as fine without them!!
Please, do not take these suggestions as critics, this is not my intention with this PR at all!
My intention solely is to help you grow and understand more about how JS and React work and what other routes can be taken to achieve the same outcome!

### CODE REVIEW

**Comment by fekete965** [comment]
@FMirzaei93 do you have any questions regarding any of these suggestions? :)

**Comment by FMirzaei93** [comment]
@fekete965 
Hi! Sorry I know it's a bit late, but I've been so busy since you worked on my project, until yesterday, that I could find some time to dig into whatever you added. I was planning to text you to thank you for the time you spend to modify my codes! 
I can say that your suggestions are a real programming course for me! Wise and thoughtful codes, great separation of codes into different modules! I was just amazed and learned so many great things.
I do have some questions that I'll ask you after I have a comprehensive overview of the whole code again.

**Comment by FMirzaei93** [comment]
Hi Bence,

I have a couple of questions regarding the modifications that you did, I'd appreciate it if you can help me.

In the useTimer hook: (I have read about all react hooks, and now I have a clear vision of what they do)
    - All the functions in this hook are using the useCallback hook, except for 'clearTimer', why is this function not using it?
    - Why do you prefer using useRef in 'const intervalRef = React.useRef(null)' over let?


In utils.modules -> Time() function:
   - What's the difference between "toJson()" function and "value", because the function also returns the "value".


In Hooks directory  -> index.js :
You're exporting both hooks by using 'export {default as useLocalStorage} from ./useLocalStorage'

   - My question: what's the "default as" keyword and what is it used for?
   (what was the difference if we would export it like : export useLocalStorage from ./useLocalStorage)


In hooks -> useLocalStorage:
   - The "best record" part of the application is not working, definitely it's related to the useLocalStorage part.
   - In the useLocalStorage hook -> your code says: "serialise : JSON.parse", while when you're using this hook in Home.js, you define "serialise: JSON.stringify". Is there any specific reason for this conflict? or am I
   wrong?

I hope these questions do not inconvenience you too much.
I appreciate your time and help.

**Comment by fekete965** [comment]
Hi @FMirzaei93 :)

1. ```All the functions in this hook are using the useCallback hook, except for 'clearTimer', why is this function not using it?```
I personally only use `React.useCallback()` if the function I use will be passed down as a prop. This way I keep the reference of the function consistent and it will avoid unnecessary re-renders.
In our case, I was a bit hesitant to memoise the `clearTimer` function. I did an experiment to use it without memoisation and everything worked like a charm so I decided to leave it this way.
We could have wrapped it into a `React.useCallback()` but then we would have needed to define its own dependency list, and update all the other functions dep list which use this function. 

Looking at the code now I might have wrapped it into a `React.useCallback()` haha 😂 
I don't think it would impact the performance of the application in any way.

If you prefer to have this function memoised just go for it :)

2. ```Why do you prefer using useRef in "const intervalRef = React.useRef(null)" over let?```
I love treating every data in my application as they are immutables, hence I always use `const`.
Don't take me wrong, there is no problem with `let` I just personally love the immutable approach and I love solving my problems that way.

Also in this scenario, I will never change `intervalRef`, I will change the `.current` property on the object.
If I would have changed `intervalRef` itself, without clearing the interval first, we would have double intervals running at the same time.

3. ```What's the difference between "toJson()" function and "value", because  the function also returns the "value".```
This is actually very interesting.
When you use `JSON.stringify()` and your data type has a property called `.toJson()`, that method's being used for serialisation. In our case we have an object, which has a bunch of methods, and a property called `value`.
It was easier to store the `value` itself as a number instead of an object with a property of `value`

An example how the object would look like without `.toJson()` defined:
```
my-localstorage-key: { value: 0 }
```
Instead of this, we will return the value itself and we end up storing the number itself:
```
my-localstorage-key: 0
```

Here is the MDN documentation if you want to read more:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior

4. ```You're exporting both hooks by using "export {default as useLocalStorage} from ./useLocalStorage". My question: what's the "default as" keyword and what is it used for? (what was the difference if we would export it like : export   useLocalStorage from ./useLocalStorage)```

`default as` will pick up the default export from the file then you can rename anything you'd like.
We basically saying, import this default export and export it as XYZ.
Unfortunately, the following syntax it not valid:
```export useLocalStorage from ./useLocalStorage```

This is also comes down to personal a preference but the following scenario is also not super far fetched, I went through this a few times:
- You start working on a project and you created a `utils.js` or `utils.ts`
- You have 2 max 4 utility functions in that file. It is not too crowded still easy to read.
- You work a couple more days on the project and all of the sudden your `utils.js` or `utils.ts` have 15 utility fns
- Now readibilty become a bit unpleasant, so you have decided to create a `utils` folder instead and to create maybe 3-4 files for your utils since you could group them up somehow nicely like: formatters, transformers, requests or something.
- Great, but now you have to go through your whole project and update the imports 🤦‍♀️ (Well, that's a bit of a pain in the bum, but it can be done it just takes time)
- Instead of doing it the hard way, you can create an `index.js` or `index.ts` which will be a collection of your util functions.
Since you already have your imports in your project using the modular syntax: ```import { formatBoolean, transformTodoData } from '../utils'```
You will not need to go through your project and update the imports. Having an `index` file in your folder will help the compiler to pick it up automatically if you refer to the folder itself, you don't need to specify the `index.js` or `index.ts` etc... 

5. ```First of all, this hook and the way that you have used it iscomplicated for me :( I'm having a hard time understanding it 😅```
I am so sorry, I might went overboard haha 😂

If you'd like we can schedule a call and we can go through the code together and I can explain bits and bobs.

Also, somebody else asked for an exercise so I made one which is a "guide/exercise" to implement this hook:
[Click me](https://codesandbox.io/s/hwbwm5?file=/src/screens/exercise1/index.js)

Regarding the last bit. You are correct, I messed up the default option object 😓 
The application breaks because you need to clear your local storage before you use the application, since you have a different data structure saved probably.
I should have guarded the parsing, sorry!! 😵‍💫

**Comment by FMirzaei93** [comment]
Thank you for the time you made to answer my questions, I'd appreciate it, my friend :)
I'll check them out :)

**Comment by fekete965** [comment]
@FMirzaei93 I'm very happy to help! :) I can try to write down how the useLocalStorage hook works but it might take a bit of time 😅  That's why I suggested the call if you are not too busy nowadays, I can see you are one of the smartest devs out there based on your CV haha 😆

**Comment by FMirzaei93** [comment]
Sorry if I reply with lateness, these days I'm quite busy.
Thank you, I got almost everything you wrote.
I guess I need to do some small simplifications for myself just to follow the code easier if you don't mind.

**Comment by fekete965** [comment]
@FMirzaei93 you reply when you have time and if you want to 😆 

The most simple implementation of the `useLocalStorage` covers the following:
- custom hook which takes in a `key` and a `defaultValue`
- the hook returns the `data/state` and `dispatcher/setter`
- on `data/state` change, we should update the `localStorage`
- on `key` change, we should remove the data stored under the old `key`

`React.useState()` can take in a `value` as the default value or a `fn`.
(If you have a heavy computation as the default value, you can pass a function which will do the computation and it will keep the UI unblocked)
In our case, we use the function to "branch" out according to the type of the value in the `localStorage` and the type of the `defaultValue`

- The options object is not necessary, it just makes the hook more flexible.
- Guarding the data parsing is also an addition, somebody might want to mess with the `localStorage`.
- Listening to the `localStore` changes and updating the state accordingly can also be an addition, since if we have the application open in multiple browser tabs and we updated the `localStore`, the other tabs will still have the old data in memory until we refresh the page.

**Pull request merged**
